### ISSUE TITLE
When starting config with backslash parsing fails

### ISSUE THREAD

**Issue by bpradeep20** [etingof/apacheconfig#35]
For below config:

```
# comment
\
<main>
    key value
</main>
```

This is raising an error:

>     raise ApacheConfigError("Illegal character '%s'" % t.value[0])
> apacheconfig.error.ApacheConfigError: Illegal character '\'

while perl parser parse it properly.

I am not sure whether perl's behavior is correct but just wanted to bring it to your notice.

Also it might be related to https://github.com/etingof/apacheconfig/issues/34.

Can you please check?

**Comment by etingof** [comment]
Hopefully fixed by commit 08d42cb40f351117dab76691284f984f17e4b4ac which is in master.

**Comment by Sumit3** [comment]
This issue is occurring for me again. I checked the my checkout has the fixes present in above commit but i still receive the above error
